import { AIModel, Challenge, Sandbox, TrustMarkCertification } from "@/types";

export const MOCK_MODELS: AIModel[] = [
  {
    id: "mdl-001",
    name: "ClinicalDX Radiology",
    description: "AI-powered radiology image analysis for early detection of pulmonary conditions using chest X-rays and CT scans.",
    category: "Medical Imaging",
    guild: "healthcare",
    version: "2.1.0",
    status: "certified",
    trustMarkLevel: "gold",
    metrics: { accuracy: 96.4, latency: 120, throughput: 500 },
    tags: ["radiology", "imaging", "diagnostics"],
    updatedAt: "2026-03-15",
  },
  {
    id: "mdl-002",
    name: "GenomicsEngine",
    description: "Whole genome sequencing analysis pipeline for pharmacogenomics and rare disease identification.",
    category: "Genomics",
    guild: "healthcare",
    version: "1.3.0",
    status: "deployed",
    trustMarkLevel: "silver",
    metrics: { accuracy: 99.1, latency: 3600, throughput: 50 },
    tags: ["genomics", "pharmacogenomics", "sequencing"],
    updatedAt: "2026-03-10",
  },
  {
    id: "mdl-003",
    name: "BuildingIQ Twin",
    description: "Digital twin engine for real-time building energy optimization and predictive maintenance scheduling.",
    category: "Digital Twin",
    guild: "proptech",
    version: "3.0.1",
    status: "deployed",
    trustMarkLevel: "gold",
    metrics: { accuracy: 91.2, latency: 50, throughput: 2000 },
    tags: ["digital-twin", "energy", "maintenance"],
    updatedAt: "2026-03-18",
  },
  {
    id: "mdl-004",
    name: "SmartSpace Occupancy",
    description: "Computer vision model for real-time occupancy detection and space utilization analytics.",
    category: "Computer Vision",
    guild: "proptech",
    version: "1.5.0",
    status: "certified",
    metrics: { accuracy: 94.8, latency: 30, throughput: 5000 },
    tags: ["occupancy", "computer-vision", "analytics"],
    updatedAt: "2026-02-28",
  },
  {
    id: "mdl-005",
    name: "Plantortion Intelligence",
    description: "Precision agriculture AI for palm oil yield prediction and optimal harvest scheduling using satellite and IoT data.",
    category: "Agriculture AI",
    guild: "agrifood",
    version: "1.0.0",
    status: "testing",
    metrics: { accuracy: 87.3, latency: 200, throughput: 100 },
    tags: ["agriculture", "yield", "satellite"],
    updatedAt: "2026-03-20",
  },
  {
    id: "mdl-006",
    name: "ESG Reporter",
    description: "Automated ESG metric collection and reporting engine for agricultural operations and supply chains.",
    category: "ESG & Compliance",
    guild: "agrifood",
    version: "0.9.0",
    status: "draft",
    metrics: { accuracy: 85.0 },
    tags: ["esg", "compliance", "reporting"],
    updatedAt: "2026-03-05",
  },
  {
    id: "mdl-007",
    name: "DemandCast QSR",
    description: "Hyper-local demand forecasting for quick-service restaurants using weather, events, and historical sales data.",
    category: "Demand Forecasting",
    guild: "food-services",
    version: "1.2.0",
    status: "testing",
    metrics: { accuracy: 89.5, latency: 80, throughput: 1000 },
    tags: ["forecasting", "qsr", "demand"],
    updatedAt: "2026-03-22",
  },
  {
    id: "mdl-008",
    name: "HalalTrace Chain",
    description: "Blockchain-integrated Halal traceability system for farm-to-fork supply chain verification.",
    category: "Traceability",
    guild: "food-services",
    version: "0.8.0",
    status: "draft",
    metrics: { accuracy: 99.9 },
    tags: ["halal", "traceability", "blockchain"],
    updatedAt: "2026-03-01",
  },
];

export const MOCK_CHALLENGES: Challenge[] = [
  {
    id: "ch-001",
    title: "Early Detection of Diabetic Retinopathy",
    description: "Develop an AI model to screen for diabetic retinopathy from fundus photographs with >95% sensitivity.",
    guild: "healthcare",
    status: "open",
    postedBy: "KPJ Clinical Research",
    submissions: 3,
    matchScore: 92,
    tags: ["ophthalmology", "imaging", "screening"],
    createdAt: "2026-02-15",
    deadline: "2026-06-30",
  },
  {
    id: "ch-002",
    title: "Smart HVAC Optimization",
    description: "Create a reinforcement learning agent to optimize HVAC systems in tropical commercial buildings, targeting 25% energy reduction.",
    guild: "proptech",
    status: "in_progress",
    postedBy: "JLand Facilities",
    submissions: 5,
    matchScore: 88,
    tags: ["energy", "hvac", "reinforcement-learning"],
    createdAt: "2026-01-20",
    deadline: "2026-05-15",
  },
  {
    id: "ch-003",
    title: "Palm Oil Yield Prediction",
    description: "Build a model combining satellite imagery and soil sensor data to predict palm oil fresh fruit bunch yields within 10% accuracy.",
    guild: "agrifood",
    status: "open",
    postedBy: "Kulim Plantations",
    submissions: 1,
    matchScore: 95,
    tags: ["agriculture", "prediction", "satellite"],
    createdAt: "2026-03-01",
    deadline: "2026-09-30",
  },
  {
    id: "ch-004",
    title: "Food Waste Reduction Dashboard",
    description: "Design an intelligent dashboard that predicts daily food waste and recommends portion adjustments for QSR outlets.",
    guild: "food-services",
    status: "open",
    postedBy: "QSR Brands Operations",
    submissions: 0,
    matchScore: 85,
    tags: ["food-waste", "dashboard", "prediction"],
    createdAt: "2026-03-10",
    deadline: "2026-08-31",
  },
];

export const MOCK_SANDBOXES: Sandbox[] = [
  {
    id: "sb-001",
    name: "Radiology AI Development",
    guild: "healthcare",
    owner: "Dr. Ahmad Razak",
    status: "running",
    resources: { cpu: 8, memory: 32, gpu: 1, storage: 500 },
    createdAt: "2026-03-01",
    expiresAt: "2026-06-01",
  },
  {
    id: "sb-002",
    name: "Digital Twin Prototype",
    guild: "proptech",
    owner: "Eng. Sarah Lim",
    status: "running",
    resources: { cpu: 16, memory: 64, gpu: 2, storage: 1000 },
    createdAt: "2026-02-15",
    expiresAt: "2026-05-15",
  },
  {
    id: "sb-003",
    name: "Yield Prediction Testing",
    guild: "agrifood",
    owner: "Dr. Mei Ling",
    status: "provisioning",
    resources: { cpu: 4, memory: 16, gpu: 1, storage: 200 },
    createdAt: "2026-03-20",
    expiresAt: "2026-06-20",
  },
];

export const MOCK_CERTIFICATIONS: TrustMarkCertification[] = [
  {
    id: "tm-001",
    modelId: "mdl-001",
    modelName: "ClinicalDX Radiology",
    level: "gold",
    status: "certified",
    criteria: [
      { name: "Bias Assessment", passed: true, score: 95 },
      { name: "Explainability", passed: true, score: 90 },
      { name: "Security Audit", passed: true, score: 98 },
      { name: "Clinical Validation", passed: true, score: 96 },
      { name: "Data Privacy Compliance", passed: true, score: 100 },
      { name: "Halal/Ethical Compliance", passed: true, score: 92 },
    ],
    issuedAt: "2026-02-01",
    expiresAt: "2027-02-01",
  },
  {
    id: "tm-002",
    modelId: "mdl-003",
    modelName: "BuildingIQ Twin",
    level: "gold",
    status: "certified",
    criteria: [
      { name: "Bias Assessment", passed: true, score: 88 },
      { name: "Explainability", passed: true, score: 92 },
      { name: "Security Audit", passed: true, score: 95 },
      { name: "Performance Benchmark", passed: true, score: 91 },
      { name: "Data Privacy Compliance", passed: true, score: 97 },
      { name: "ESG Impact Assessment", passed: true, score: 89 },
    ],
    issuedAt: "2026-01-15",
    expiresAt: "2027-01-15",
  },
];
